version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service:latest3
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/authserver_db
      - SPRING_DATASOURCE_USERNAME=ykh12
      - SPRING_DATASOURCE_PASSWORD=password
    networks:
      - auth-network
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=authserver_db
      - POSTGRES_USER=ykh12
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
